document.addEventListener("DOMContentLoaded",()=>{
const menu=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");menu?.addEventListener("click",()=>{const o=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(o))});
document.querySelectorAll("[data-year]").forEach(e=>e.textContent=new Date().getFullYear());
const toast=document.querySelector(".toast");function show(m){if(!toast)return;toast.textContent=m;toast.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove("show"),3300)}
document.querySelectorAll(".demo-form").forEach(f=>f.addEventListener("submit",e=>{e.preventDefault();if(!f.reportValidity())return;f.reset();show("Demo submitted. Connect this form to a backend before launch.")}));
const gen=document.querySelector("#generate-plan"),result=document.querySelector("#planner-result");if(gen&&result){gen.addEventListener("click",()=>{const exam=document.querySelector("#exam-select").value,weeks=+document.querySelector("#weeks-select").value;const phase=(w)=>w===1?"Baseline diagnostic and setup":w/weeks<=.35?"Foundation review and focused concept practice":w/weeks<=.68?"Mixed drills, speed building, and error-log review":w/weeks<=.88?"Timed sections and mock-test simulations":"Target weak areas, taper workload, and prepare test-day routines";let h=`<div class="generated-plan"><h3>${exam}: ${weeks}-Week Starter Roadmap</h3>`;for(let w=1;w<=weeks;w++)h+=`<div class="plan-week"><b>Week ${w}</b><span>${phase(w)}</span></div>`;result.innerHTML=h+"</div>";localStorage.setItem("tutodemyPlan",JSON.stringify({exam,weeks}))})}
const cards=[...document.querySelectorAll(".library-grid article")],search=document.querySelector("#resource-search"),filters=[...document.querySelectorAll("[data-filter]")],count=document.querySelector("#resource-count"),no=document.querySelector("#no-results");let active="all";function apply(){if(!cards.length)return;const term=(search?.value||"").toLowerCase().trim();let n=0;cards.forEach(c=>{const ok=(active==="all"||(c.dataset.category||"").includes(active))&&(!term||c.textContent.toLowerCase().includes(term)||(c.dataset.title||"").toLowerCase().includes(term));c.hidden=!ok;if(ok)n++});if(count)count.textContent=`${n} resource${n===1?"":"s"}`;if(no)no.hidden=n!==0}search?.addEventListener("input",apply);filters.forEach(b=>b.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));b.classList.add("active");active=b.dataset.filter;apply()}));
const dialog=document.querySelector("#resource-dialog"),title=document.querySelector("#dialog-title");document.querySelectorAll(".resource-open").forEach(b=>b.addEventListener("click",()=>{title.textContent=b.dataset.resource;dialog.showModal()}));document.querySelector(".dialog-close")?.addEventListener("click",()=>dialog.close());document.querySelector(".demo-download")?.addEventListener("click",()=>show("Demo only: attach a real PDF or lesson page here."));
});
